"""Add gamified loyalty and marketing automation

Revision ID: a919e7a4ef3e
Revises: ecac43ff0ce0
Create Date: 2026-01-09 11:32:10.414234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a919e7a4ef3e'
down_revision = 'ecac43ff0ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('badge_type', sa.String(length=32), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('criteria_type', sa.String(length=32), nullable=True),
    sa.Column('criteria_value', sa.Integer(), nullable=True),
    sa.Column('points_reward', sa.Integer(), nullable=True),
    sa.Column('discount_reward', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_badges_code'), ['code'], unique=True)

    op.create_table('automated_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_days', sa.Integer(), nullable=True),
    sa.Column('trigger_conditions', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('times_triggered', sa.Integer(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['sms_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['loyalty_badges.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'badge_id', name='uix_customer_badge')
    )
    with op.batch_alter_table('customer_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_badges_customer_id'), ['customer_id'], unique=False)

    op.create_table('loyalty_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('challenge_type', sa.String(length=32), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reward_type', sa.String(length=32), nullable=True),
    sa.Column('reward_value', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['loyalty_badges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('referrer_reward', sa.Integer(), nullable=True),
    sa.Column('referred_reward', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('qualified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_referral_code'), ['referral_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_referred_id'), ['referred_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_referrer_id'), ['referrer_id'], unique=False)

    op.create_table('sms_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('campaign_type', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('target_audience', sa.String(length=32), nullable=True),
    sa.Column('target_criteria', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('recurring_schedule', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('delivered_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['sms_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_challenge_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reward_claimed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['loyalty_challenges.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'challenge_id', name='uix_customer_challenge')
    )
    with op.batch_alter_table('customer_challenge_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_challenge_progress_customer_id'), ['customer_id'], unique=False)

    op.create_table('digital_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('delivery_method', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('receipt_token', sa.String(length=64), nullable=True),
    sa.Column('qr_code_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digital_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digital_receipts_receipt_token'), ['receipt_token'], unique=True)

    op.create_table('trigger_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('message_sent', sa.Boolean(), nullable=True),
    sa.Column('channel_used', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['automated_triggers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trigger_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trigger_logs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trigger_logs_trigger_id'), ['trigger_id'], unique=False)

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_activity_logs_action_timestamp', ['action', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_activity_logs_user_timestamp', ['user_id', 'timestamp'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_preference', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_optin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_optin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_optin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('referral_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('referred_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_referral_code'), ['referral_code'], unique=True)
        batch_op.create_foreign_key('fk_customers_referred_by_id', 'customers', ['referred_by_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_split_payment', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_password_change', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('force_password_change')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_customer_id'))
        batch_op.drop_column('is_split_payment')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_order')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_referral_code'))
        batch_op.drop_column('referred_by_id')
        batch_op.drop_column('referral_code')
        batch_op.drop_column('sms_optin')
        batch_op.drop_column('email_optin')
        batch_op.drop_column('whatsapp_optin')
        batch_op.drop_column('receipt_preference')

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_logs_user_timestamp')
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index('ix_activity_logs_action_timestamp')
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))

    with op.batch_alter_table('trigger_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trigger_logs_trigger_id'))
        batch_op.drop_index(batch_op.f('ix_trigger_logs_customer_id'))

    op.drop_table('trigger_logs')
    with op.batch_alter_table('digital_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digital_receipts_receipt_token'))

    op.drop_table('digital_receipts')
    with op.batch_alter_table('customer_challenge_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_challenge_progress_customer_id'))

    op.drop_table('customer_challenge_progress')
    op.drop_table('sms_campaigns')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_referrer_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_referred_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_referral_code'))

    op.drop_table('referrals')
    op.drop_table('loyalty_challenges')
    with op.batch_alter_table('customer_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_badges_customer_id'))

    op.drop_table('customer_badges')
    op.drop_table('automated_triggers')
    with op.batch_alter_table('loyalty_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_badges_code'))

    op.drop_table('loyalty_badges')
    # ### end Alembic commands ###
