"""Sync database state after manual column additions

Revision ID: b6bb3cbb8470
Revises: a919e7a4ef3e
Create Date: 2026-01-09 11:43:03.761990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bb3cbb8470'
down_revision = 'a919e7a4ef3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add indexes to customers table
    with op.batch_alter_table('customers', schema=None) as batch_op:
        try:
            batch_op.create_index(batch_op.f('ix_customers_referral_code'), ['referral_code'], unique=True)
        except Exception:
            pass  # Index may already exist
        try:
            batch_op.create_foreign_key('fk_customers_referred_by_id', 'customers', ['referred_by_id'], ['id'])
        except Exception:
            pass  # FK may already exist

    # Add indexes to sales table
    with op.batch_alter_table('sales', schema=None) as batch_op:
        try:
            batch_op.create_index(batch_op.f('ix_sales_customer_id'), ['customer_id'], unique=False)
        except Exception:
            pass
        try:
            batch_op.create_index(batch_op.f('ix_sales_user_id'), ['user_id'], unique=False)
        except Exception:
            pass

    # Update sms_campaigns foreign key
    with op.batch_alter_table('sms_campaigns', schema=None) as batch_op:
        try:
            batch_op.create_foreign_key('fk_sms_campaigns_created_by_id', 'users', ['created_by_id'], ['id'])
        except Exception:
            pass

    # Add columns to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        try:
            batch_op.add_column(sa.Column('force_password_change', sa.Boolean(), nullable=True))
        except Exception:
            pass
        try:
            batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), nullable=True))
        except Exception:
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        try:
            batch_op.drop_column('password_changed_at')
        except Exception:
            pass
        try:
            batch_op.drop_column('force_password_change')
        except Exception:
            pass

    with op.batch_alter_table('sms_campaigns', schema=None) as batch_op:
        try:
            batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        except Exception:
            pass
        try:
            batch_op.drop_constraint('fk_sms_campaigns_created_by_id', type_='foreignkey')
        except Exception:
            pass
        try:
            batch_op.create_foreign_key('fk_sms_campaigns_created_by', 'users', ['created_by'], ['id'])
        except Exception:
            pass

    with op.batch_alter_table('sales', schema=None) as batch_op:
        try:
            batch_op.drop_index(batch_op.f('ix_sales_user_id'))
        except Exception:
            pass
        try:
            batch_op.drop_index(batch_op.f('ix_sales_customer_id'))
        except Exception:
            pass

    with op.batch_alter_table('customers', schema=None) as batch_op:
        try:
            batch_op.drop_constraint('fk_customers_referred_by_id', type_='foreignkey')
        except Exception:
            pass
        try:
            batch_op.drop_index(batch_op.f('ix_customers_referral_code'))
        except Exception:
            pass

    # ### end Alembic commands ###
